arch:
  - amd64
  - ppc64le
language: go

go:
  - 1.13.x

install:
  - make install-travis

script:
  - GOFLAGS="-mod=vendor" make verify
  - GOFLAGS="-mod=vendor" make check TESTFLAGS="-p=4" TESTS="''" # empty quotes are because hack/test-go.sh requires 2 args

notifications:
  irc: "chat.freenode.net#openshift-dev"

sudo: false

matrix:
  allow_failures:
  - go: master
  fast_finish: true
