language: go

go:
  - 1.6.2
  - 1.7.1

install:
  - make install-travis

script:
  - make verify
  - make check TESTFLAGS="-p=4" TESTS="''" # empty quotes are because hack/test-go.sh requires 2 args

notifications:
  irc: "chat.freenode.net#openshift-dev"

sudo: false
