language: go

go:
  - 1.4

install:
  - go get golang.org/x/tools/cmd/cover
  - go get -u github.com/golang/lint/golint
  - ./hack/verify-gofmt.sh
  - ./hack/verify-golint.sh || true
  - ./hack/build-go.sh

script:
  - STI_RACE="-race" STI_COVER="-cover -covermode=atomic" ./hack/test-go.sh "" -p=4

notifications:
  irc: "chat.freenode.net#openshift-dev"
